{
 "title": "Evidently Metrics",
 "time": { "from": "2024-02-29T22:00:00.000Z", "to": "2024-03-30T22:00:00.000Z" },
 "panels": [
  {
   "title": "Missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,share_missing_values FROM dummy_metrics;"
    }
   ]
  },
  {
   "title": "Fare amount quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,fare_amount_quantile FROM dummy_metrics;"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,num_drifted_columns FROM dummy_metrics;"
    }
   ]
  },
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,prediction_drift FROM dummy_metrics;"
    }
   ]
  }
 ]
}