FROM python:3.10-slim

RUN pip install mlflow==2.12.1

EXPOSE 5000

ENV MLFLOW_DATABASE_CONNECTION_URL="sqlite:///home/mlflow_data/mlflow.db"

CMD [ \
    "mlflow", "server", \
    "--backend-store-uri", "${MLFLOW_DATABASE_CONNECTION_URL}", \
    "--host", "0.0.0.0", \
    "--port", "5000" \
]
